spring:
  flyway:
    url: jdbc://database/twitch
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
  application:
    name: twitch-followers-scanner
  security:
    oauth2:
      client:
        provider:
          twitch:
            issuer-uri: https://id.twitch.tv/oauth2
        registration:
          twitch:
            provider: twitch
            client-id: ${twitch.client-id}
            client-secret: ${twitch.client-secret}
            client-authentication-method: client_secret_post
            scope:
              - openid
              - moderator:read:followers
  data:
    redis:
      repositories:
        enabled: false

server:
  forward-headers-strategy: native
  error:
    include-message: always
  reactive:
    session:
      timeout: 30d

management:
  endpoints:
    web.exposure.include: health,prometheus

---
spring:
  config:
    activate:
      on-profile: process-aot
  r2dbc:
    url: r2dbc:postgres://none/none