spring:
  application:
    name: twitch-followers-scanner
  r2dbc:
    url: ${postgres.url}
    username: ${postgres.username}
    password: ${postgres.password}
  security:
    oauth2:
      client:
        provider:
          twitch:
            issuer-uri: https://id.twitch.tv/oauth2
        registration:
          twitch:
            provider: twitch
            client-id: ${twitch.client-id}
            client-secret: ${twitch.client-secret}
            scope:
              - openid
              - moderator:read:followers